---
ansible_become: false
system_is_container: true
skip_reboot: true
rhel9cis_disruption_high: false

# Audit
rhel9cis_level_2: false
setup_audit: true
run_audit: true

rhel9cis_rule_3_1_2: false
rhel9cis_rule_4_1_2: false
rhel9cis_rule_5_4_2_5: false
rhel9cis_rule_6_3_1_1: false
rhel9cis_rule_6_3_1_2: false
rhel9cis_rule_6_3_1_3: false
rhel9cis_rule_6_3_1_4: false
rhel9cis_rule_7_1_11: false

rhel9cis_allow_authselect_updates: false
rhel9cis_bootloader_password_hash: "grub.pbkdf2.sha512.10000.D5BFAB2173271AAD8D2E91CEC85D334390C44CC045FA43272967B2EEDB51E8C9CA29605BCBDACF5517838CE037B6ED38A06F11FC0FC4DBF9EC9F1F15D386EDD5.F6D2DF1AD9E3BB839E91FA38BB8B5210B85B9E02AE644A082DED07BD8511EFE87D6DFE48C84002E900BAED8CB8B01CBC9AED07B8013E5484C9C0682A69DFB905"
rhel9cis_authselect_custom_profile_name: molecule_cis_profile

rhel9cis_syslog: journald
